language: c

matrix:
    include:
        - os: linux
          sudo: required
          env:
            - PACKAGE=freedv-dev
        - os: osx
          language: generic
          env:
            - PACKAGE=freedv-dev
        - os: linux
          sudo: required
          env:
            - PACKAGE=freedv
        - os: osx
          language: generic
          env:
            - PACKAGE=freedv

script: cd $PACKAGE && cmake - && make
