language: c
os: linux
sudo: required
env:
    - PLATFORM=linux
addons:
  apt:
    packages:
        - tree
        - libspeexdsp-dev
        - libsamplerate-dev
        - libwxgtk3.0-dev
        - portaudio19-dev
        - libhamlib-dev
        - libsamplerate-dev
        - libasound2-dev
        - libao-dev
        - libgsm1-dev
        - libsndfile-dev
script: cd $PACKAGE && mkdir build_$PLATFORM && cd build_$PLATFORM && cmake $CMAKE_ARGS ../ && make && tree -f -h

jobs:
    include:
        - stage: build codec2
          env:
            - PACKAGE=codec2-dev
            - CMAKE_ARGS=-
        - stage: build freedv-dev
          env:
            - PACKAGE=freedv-dev
            - CMAKE_ARGS=-DBOOTSTRAP_WXWIDGETS=TRUE
