#ifndef FREEDV_VER_DOT_H
#define FREEDV_VER_DOT_H 1

#define FREEDV_VERSION_MAJOR 0
#define FREEDV_VERSION_MINOR 98
#define FREEDV_VERSION_PATCH 0
#define FREEDV_VERSION_SUFFIX "Beta"

#define FREEDV_VERSION "0.98.0 Beta"

#endif //FREEDV_VER_DOT_H
